set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
if(NOT APPLE)
    message(FATAL_ERROR "FreeLLM's native engine requires Apple Silicon/macOS")
endif()
enable_language(OBJCXX)
set(CMAKE_OBJCXX_STANDARD 23)
set(CMAKE_OBJCXX_STANDARD_REQUIRED ON)
include(FetchContent)
FetchContent_Declare(json GIT_REPOSITORY https://github.com/nlohmann/json.git GIT_TAG v3.11.3 GIT_SHALLOW TRUE)
FetchContent_MakeAvailable(json)
set(MINJA_TEST_ENABLED OFF CACHE BOOL "" FORCE)
set(MINJA_EXAMPLE_ENABLED OFF CACHE BOOL "" FORCE)
set(MINJA_FUZZTEST_ENABLED OFF CACHE BOOL "" FORCE)
set(MINJA_USE_VENV OFF CACHE BOOL "" FORCE)
FetchContent_Declare(minja GIT_REPOSITORY https://github.com/google/minja.git GIT_TAG 021c2293c187789ef13d56c6cfd89c9b134fd80f)
FetchContent_MakeAvailable(minja)
file(READ "${CMAKE_SOURCE_DIR}/kernels/metal/qwen.metal" FREELLM_METAL_SOURCE)
file(READ "${CMAKE_SOURCE_DIR}/models.lock.json" FREELLM_MODEL_LOCK)
file(READ "${CMAKE_SOURCE_DIR}/mixed-models.lock.json" FREELLM_MIXED_MODEL_LOCK)
file(READ "${CMAKE_SOURCE_DIR}/mixed-payload-reuse.lock.json" FREELLM_MIXED_REUSE_LOCK)
file(GLOB FREELLM_BUILD_INPUTS CONFIGURE_DEPENDS "${CMAKE_SOURCE_DIR}/src/qwen/*" "${CMAKE_SOURCE_DIR}/include/qwen/*")
list(APPEND FREELLM_BUILD_INPUTS "${CMAKE_SOURCE_DIR}/kernels/metal/qwen.metal" "${CMAKE_SOURCE_DIR}/models.lock.json" "${CMAKE_SOURCE_DIR}/mixed-models.lock.json" "${CMAKE_SOURCE_DIR}/mixed-payload-reuse.lock.json" "${CMAKE_SOURCE_DIR}/cmake/qwen.cmake")
set(FREELLM_BUILD_IDENTITY "")
foreach(input IN LISTS FREELLM_BUILD_INPUTS)
    file(SHA256 "${input}" digest)
    file(RELATIVE_PATH label "${CMAKE_SOURCE_DIR}" "${input}")
    string(APPEND FREELLM_BUILD_IDENTITY "${label}:${digest}\n")
endforeach()
string(SHA256 FREELLM_BUILD_FINGERPRINT "${FREELLM_BUILD_IDENTITY}")
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${FREELLM_BUILD_INPUTS})
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
    "${CMAKE_SOURCE_DIR}/kernels/metal/qwen.metal" "${CMAKE_SOURCE_DIR}/models.lock.json")
configure_file(cmake/qwen_embedded.hpp.in generated/qwen_embedded.hpp @ONLY)
add_library(freellm_lib STATIC
    src/qwen/storage.cpp src/qwen/metal.mm src/qwen/model.cpp src/qwen/prefill.cpp src/qwen/pipeline.cpp src/qwen/bench.cpp src/qwen/kernel_bench.cpp src/qwen/cached_replay.cpp
    src/qwen/tokenizer.mm src/qwen/session.cpp src/qwen/server.cpp)
target_include_directories(freellm_lib PUBLIC include PRIVATE ${minja_SOURCE_DIR}/include ${CMAKE_BINARY_DIR}/generated)
target_link_libraries(freellm_lib PUBLIC nlohmann_json::nlohmann_json PRIVATE "-framework Metal" "-framework Foundation" "-framework IOKit")
target_compile_options(freellm_lib PRIVATE -Wall -Wextra -Wpedantic -Werror -fno-fast-math)
set_source_files_properties(src/qwen/metal.mm src/qwen/tokenizer.mm PROPERTIES COMPILE_FLAGS "-fobjc-arc")
add_executable(freellm src/qwen/main.cpp)
target_link_libraries(freellm PRIVATE freellm_lib)
set_target_properties(freellm PROPERTIES RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
install(TARGETS freellm freellm_lib RUNTIME DESTINATION bin ARCHIVE DESTINATION lib)
install(DIRECTORY include/qwen DESTINATION include)
enable_testing()
add_executable(test_qwen tests/test_qwen.cpp)
target_include_directories(test_qwen PRIVATE external)
target_link_libraries(test_qwen PRIVATE freellm_lib)
add_test(NAME QwenNative COMMAND test_qwen)
add_executable(qwen_moe_replay scripts/qwen/replay_moe.cpp)
target_link_libraries(qwen_moe_replay PRIVATE freellm_lib)
add_executable(qwen_attention_replay scripts/qwen/replay_attention.cpp)
target_link_libraries(qwen_attention_replay PRIVATE freellm_lib)
add_executable(qwen_storage_check scripts/qwen/check_storage.cpp)
target_link_libraries(qwen_storage_check PRIVATE freellm_lib)
add_executable(qwen_q8_check scripts/qwen/check_q8.cpp)
target_link_libraries(qwen_q8_check PRIVATE freellm_lib)
add_executable(qwen_route_check scripts/qwen/check_route.cpp)
target_link_libraries(qwen_route_check PRIVATE freellm_lib)
add_executable(qwen_panel_check scripts/qwen/check_panel.cpp)
target_link_libraries(qwen_panel_check PRIVATE freellm_lib)
add_executable(qwen_sparse_replay scripts/qwen/replay_sparse.cpp)
target_link_libraries(qwen_sparse_replay PRIVATE freellm_lib)
add_executable(qwen_cached_recovery scripts/qwen/check_cached_recovery.cpp)
target_link_libraries(qwen_cached_recovery PRIVATE freellm_lib)
add_executable(qwen_ple_replay scripts/qwen/replay_ple.cpp)
target_link_libraries(qwen_ple_replay PRIVATE freellm_lib)
option(FREELLM_REAL_MODEL_TESTS "Require the pinned model for explicit integration checks" OFF)
set(FREELLM_MODEL_DIR "${CMAKE_SOURCE_DIR}/.cache/models/qwen38-flash-next" CACHE PATH "Pinned model directory")
if(FREELLM_REAL_MODEL_TESTS)
    add_test(NAME QwenRealModel COMMAND freellm bench --model ${FREELLM_MODEL_DIR} --prompt "The capital of France is" --max-tokens 8 --repetitions 1)
    set_tests_properties(QwenRealModel PROPERTIES LABELS "real-model" TIMEOUT 1200)
endif()

install(FILES THIRD_PARTY_NOTICES.md DESTINATION share/freellm)
install(DIRECTORY docs/licenses/ DESTINATION share/freellm/licenses)
install(DIRECTORY "${json_SOURCE_DIR}/include/nlohmann" DESTINATION include)
install(FILES "${json_SOURCE_DIR}/LICENSE.MIT" DESTINATION share/freellm/licenses RENAME nlohmann-json.txt)
